### ISSUE TITLE
map遍历后无法传进去值？

### ISSUE THREAD

**Issue by xiaoForest** [xPixv/Taro-ParserRichText#1]
<View className='txt'>A{index+2}</View> // A2
                  <View className='txt'>B{item[index+2].data}</View>//B +无法打印
                  <View className='txt'>-----------------------</View>
                  <View className='txt'>C{tabList[index+2].data}</View> // C 获取的数组
                  {/* <ParserRichText html={tabList[index+2].data}></ParserRichText> */} // 红色报错
![2](https://user-images.githubusercontent.com/42957993/68021515-9091f500-fcdc-11e9-87f4-e1a93b7afc8b.png)
![WeChat Image_20191101191908](https://user-images.githubusercontent.com/42957993/68021516-912a8b80-fcdc-11e9-94a6-6f451859a3b4.png)

`

**Comment by xiaoForest** [comment]
<ParserRichText html={result[2].data} id={result[index + 2].title}></ParserRichText> 
id 就可以顺利打印出数据，但是html里，只要加了index下标动态遍历的就不行，它只能写死的值？

微信的源生的就可以遍历
RichText nodes='{{tabList[index+2].data}}' bindtap='tap'></RichText>  

Parser 就不可以 报错 如第一个图 ，去掉index，只写个2就可以渲染出数据，加上就不行。
{/* <ParserRichText html={result[index+2].data} id={result[index + 2].title}></ParserRichText> */}

**Comment by jin-yufeng** [comment]
`tabList[index+2]` 会导致数组越界（最后两个值），值为 `undefined`，`tabList[index+2].data` 就会报错 `Cannot read property 'data' of undefined;`

------

写成 `{result[2].data}` 不会出错是因为 `2` 没有越界，和是否动态无关

------

写在 `RichText` 里可以是因为在 `wxml` 中写 `undefined.data` 是不会报错的（且显示为空），但是在 `js` 中写 `undefined.data` 是会报上述错误的
`RichText` 是原生组件
```html
<RichText nodes={tabList[index+2].data}></RichText>
```
会被直接编译成
```html
<rich-text nodes="{{tabList[index + 2].data}}"></rich-text>
```
在 `wxml` 中 `undefined.data` 不报错，仅显示为空

------

`ParserRichText` 是一个自定义组件，`taro` 进行了一个封装
```html
<ParserRichText html={tabList[index+2].data}></ParserRichText>
```
会被编译成
```html
<parser-rich-text compid="{{item.$compid__30}}"></parser-rich-text>
```
所有属性值（除了 `id` ）是在 `parserRichText.js` 里获取的，这时就会出现 `Cannot read property 'data' of undefined;`

-----

所以应该写成
```jsx
render() {
  let {tabList} = this.state;
  return (
    <View>
      {tabList.map((item,index)=>{
        return (
          <View>
            <ParserRichText html={item.data}></ParserRichText>
            {/*<ParserRichText html={tabList[index].data}></ParserRichText>*/}
          </View>
        )
      })}
    </View>
  )
}
```

**Comment by xiaoForest** [comment]
html={item.data}>
这个在map里 不用加下标嘛？
因为有多个tab，要遍历，这样写就报错  {item[index+2].data}  是从第二个开始一写index下标就报错。
辛苦了作者大大，万分感谢

**Comment by jin-yufeng** [comment]
`item` 就是遍历出来的一个对象
`item` 等价于 `tabList[index]`

**Comment by xiaoForest** [comment]
> `item` 就是遍历出来的一个对象
> `item` 等价于 `tabList[index]`

那我试试，，明天早上我试下，我前天试了好多次了呢，item和tabList还有转json后都试了，那我明天在验证下。我一写 {item[index+2].data}   加了index就报错 。嘻嘻 周末愉快

**Comment by xiaoForest** [comment]
我真觉得这是个BUG，因为id那可以传入任何参数，到了html那就不行了是加遍历index的时候，写固定值就可以渲染成功。真的，不管是item还是tablist都是一样的。我越想越不对 ( ╯□╰ )

**Comment by jin-yufeng** [comment]
上面不是说了吗
`id` 里可以写是因为 `id` 是直接写在 `wxml` 里的，`wxml` 里 `undefined.data` 是不会错的，写在 `html` 里会错是因为 `html` 这些组件的属性并没有直接写在 `wxml` 里，而是从 `parserRichText.js` 里获取的，在 `js` 里从 `undefined` 取值是会报错的
根本原因是你的数组越界了，如果 `tabList[index+2]` （`index` 就是循环的索引值，加个 `2` 最后两个元素就越界了）不是 `undefined` 就不会错，写 `tabList[index]` 或者 `item` 就没事
跟固定值动态值没有关系，你写一个 `tabList[1000].data` 照样会错的

**Comment by xiaoForest** [comment]
非常感谢 解决了，我把数据分开遍历即可，(#^.^#)，感谢作者大大提醒越界，第一次听这个词
